apiVersion: v1
kind: Service
metadata:
  name: my-vite-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-vite-app
  ports:
    - port: 80
      targetPort: 80
<<<<<<< HEAD
test1
test2
test4
test3
=======

test
>>>>>>> f7f26edd9d7ce82f018915d74088301510cc494c
