apiVersion: v1
kind: Service
metadata:
  name: my-vite-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-vite-app
  ports:
    - port: 80
      targetPort: 80
<<<<<<< HEAD
test1
test2
=======

test
>>>>>>> 6abfcf836866701893e941da43c7ff612e9984a5
