apiVersion: v1
kind: Service
metadata:
  name: my-vite-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-vite-app
  ports:
    - port: 80
      targetPort: 80
1
2
3
4
5
6

9
<<<<<<< HEAD
7
=======

>>>>>>> parent of f2c0584 (Update loadbalanser.yaml)

jbfsjnfajsa


